### ISSUE TITLE
What about supporting cloud video services? And DVD?

### ISSUE THREAD

**Issue by timofonic** [KGHustad/RipPy#1]
Hello.

I would love to scan a directory tree to convert videos to H2655+Opus, just if the conversion is worthwhile.

I also would love to be able to download from a TY playlit or an URL from any other service by usinh youtube-dl.

Can this be feasible? What about DVD support?

I'll explain my reaons and further explanation later, but I wanted to write this before forgetting to do it.

I found some tools, but they are  some combination of the following:
- They aren't multiplatform.
- THey lack automation features.
- Most don't support online videos.
- They haven't been updated in years.

https://handbrake.fr/ https://github.com/4pr0n/rip
https://github.com/ozok/TEncoder  http://winff.org
 ç https://github.com/always-struggling/youtube_ripper
Kind regards

I'll test your software in Linux soon.

**Comment by KGHustad** [comment]
Hi,

First of all, you should know that I'm developing this software for my personal use, but I wanted it to be openly available for any fellow blu-ray rippers. If you want to improve on it, feel free to do so, but I'm unlikely to put much effort into further development once my personal needs are satisfied. 

I aim to implement the following functionality in my program:
* Muxing of blu-ray disks to a single `.m2ts` file and additional files for chapter information and subtitles
* Transcoding in Handbrake the `.m2ts` file and accompanying files to a `.mkv` file with various presets (it appears Opus is not currently supported by Handbrake)
* A certain level of platform independence is desirable, and although AnyDVD is only available for Windows, unencrypted (or already decrypted) disks should work fine on Linux.

I may add support for DVDs, however, I do think DVDs are becoming less relevant (I haven't bought any for the past 5 years), and there are many programs for ripping DVDs already, so that is not a priority at the present time. 

I will not try to develop support for any of the following, as they clearly exceed the scope of my program:
* YouTube videos
* Cloud video services (I'm not sure exactly what you mean by this)

I will close this issue, but do feel free to open a new one, should you have any issues during your testing.
